AWSTemplateFormatVersion: 2010-09-09
Description: ELB Stack

Parameters:
  InstanceId1:
    Type: String
  SGId:
    default: Security Group Id
Resources:
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      Instances:
      - Ref: Ec2Instance1
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort:
          Ref: WebServerPort
        Protocol: HTTP
      HealthCheck:
        Target:
          Fn::Join:
          - ''
          - - 'HTTP:'
            - Ref: WebServerPort
            - "/"
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
    SecurityGroups:
      Ref: SGId
